[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/en/"
  to = "/en"
  status = 301
